const API=window.RRT_API||'https://YOUR-RRT-API.workers.dev/api';
const RULES=`Доброго времени суток, РЕКРУТ!

Поведение внутри отряда и на играх:
1.1 Мат разрешен, но не злоупотреблять им.
1.2 Запрещены оскорбления.
1.4 Запрещен NSFW-контент (порнография, шок-контент).
1.5 Запрещено злоупотребление пингом ролей.
1.6 Запрещено включать саундпад в дискорде и в игре.
1.7 Запрещено издавать громкие звуки в микрофон.
1.8 При сильном фоне используйте Push-To-Talk.
1.9 Запрещены обсуждения политики.

Слив личной информации: 2.1 Слив личной информации без согласия — бан навсегда.

TvT: 3.1 Выполнение приказов капитана обязательно. 3.2 После брифинга заглушиться в ДС и не смотреть стримы, пока жив. 3.3 Обнаружение живого человека на стриме — отстранение от игр на 2 недели и строгий выговор.

Вступление: при играх с RRT использовать [RRT-N], после получения роли RRT — [RRT].

Правила тренировок:
1) Выполнять приказ инструктора. 2) После прихода последнего ожидаемого человека — 5 минут на переодевания. 3) Дуэли только с взаимным согласием. 4) Проверки оружия/дуэли — после перемещения от спауна. 5) Не флудить в рацию. 6) На тренировке в ДС выключаем микрофон, наушники оставляем включенными. 7) Баловаться можно после игры или вдали от спауна.

Запас: действует полгода, исключения — весомые причины отсутствия.

Пароли от сервера: хранятся только в закрытом разделе и не публикуются в исходном коде.`;
let state={user:null,page:'home',guides:[],progress:{},guideKey:null,blockIndex:0,questions:[],qIndex:0,flash:''};
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
async function api(path,opt={}){const r=await fetch(API+path,{credentials:'include',headers:{'Content-Type':'application/json',...(opt.headers||{})},...opt});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'Ошибка API');return d}
function roleRank(r){return{staff:5,officer:4,unit:3,recruit:2,ticket:1}[r]||0}
function nav(){const r=roleRank(state.user.accessRole);if(r===1)return[{id:'questionnaire',t:'Опросник'}];return[{id:'home',t:'Главная'},{id:'roster',t:'Состав отряда'},{id:'questionnaire',t:'Опросник'},{id:'guide',t:'Руководства'},{id:'cabinet',t:'Личный кабинет'},{id:'rules',t:'Устав и правила'},{id:'admin',t:'Панель администратора'}].filter(x=>x.id!=='admin'||r>=5)}
function layout(){document.querySelector('#app').innerHTML=`<div class="shell"><aside class="sidebar"><div class="brand"><img src="assets/rrt-logo.gif"><h1>RAPID RESPONSE TEAM</h1><p>UNIT PORTAL</p></div><div class="nav">${nav().map(x=>`<button class="${state.page===x.id?'active':''}" onclick="go('${x.id}')">${x.t}</button>`).join('')}<button onclick="logout()">Выйти</button></div></aside><main class="main"><header class="top"><div class="title">[RRT] / ${esc(state.page.toUpperCase())}</div><div class="user-chip"><span>${esc(state.user.nickname)}</span>${state.user.avatarUrl?`<img class="avatar" src="${esc(state.user.avatarUrl)}">`:''}</div></header><section class="content" id="page"></section></main></div>`;renderPage()}
function go(p){state.page=p;layout()}
async function boot(){try{const d=await api('/me');if(d.user){state.user=d.user;layout()}else loginScreen()}catch(e){loginScreen()}}
function loginScreen(){document.querySelector('#app').innerHTML=`<div class="login"><div class="loginbox"><img class="logo" src="assets/rrt-logo.gif"><h1>RAPID RESPONSE TEAM</h1><p class="muted center">Закрытый портал подразделения</p><div class="tabs"><button class="btn" onclick="loginTab('login')">Вход</button><button class="btn ghost" onclick="loginTab('activate')">Первый вход</button></div><div id="authform"></div></div></div>`;loginTab('login')}
function loginTab(mode){document.querySelector('#authform').innerHTML=mode==='login'?`<div class="field"><label>Discord User ID</label><input id="uid" autocomplete="username"></div><div class="field"><label>Пароль</label><input id="pw" type="password" autocomplete="current-password"></div><label><input id="remember" type="checkbox"> Запомнить меня</label><button class="btn wide" onclick="doLogin()">ВОЙТИ</button>`:`<div class="notice">Первый вход: Discord User ID + одноразовый код от администратора. После активации код становится недействительным.</div><div class="field"><label>Discord User ID</label><input id="uid"></div><div class="field"><label>Одноразовый код</label><input id="code"></div><div class="field"><label>Новый пароль</label><input id="pw" type="password" autocomplete="new-password"></div><div class="field"><label>Повторите пароль</label><input id="pw2" type="password" autocomplete="new-password"></div><button class="btn wide" onclick="doActivate()">АКТИВИРОВАТЬ</button>`}
async function doLogin(){try{const d=await api('/auth/login',{method:'POST',body:JSON.stringify({userId:uid.value,password:pw.value,remember:remember.checked})});state.user=d.user;state.page='home';layout()}catch(e){alert(e.message)}}
async function doActivate(){try{if(pw.value!==pw2.value)return alert('Пароли не совпадают');const d=await api('/auth/activate',{method:'POST',body:JSON.stringify({userId:uid.value,code:code.value,password:pw.value})});state.user=d.user;state.page='home';layout()}catch(e){alert(e.message)}}
async function logout(){await api('/auth/logout',{method:'POST'});state.user=null;loginScreen()}
function renderPage(){const p=document.querySelector('#page');if(state.page==='home')return home(p);if(state.page==='cabinet')return cabinet(p);if(state.page==='roster')return roster(p);if(state.page==='rules')return rules(p);if(state.page==='questionnaire')return questionnaire(p);if(state.page==='admin')return admin(p);if(state.page==='guide')return guideHome(p)}
function serviceDays(s){if(!s)return 0;return Math.max(0,Math.floor((Date.now()-new Date(s+'T00:00:00'))/86400000))}function monthsLabel(d){const m=Math.floor(d/30.4375),y=Math.floor(m/12),r=m%12;return y?`${y} ${y===1?'год':'лет'}${r?' '+r+' мес.':''}`:`${m} мес.`}function formatDate(s){return new Date(s+'T00:00:00').toLocaleDateString('ru-RU')}
function home(p){let bd='';if(state.user.birthDate){const now=new Date(),b=new Date(state.user.birthDate+'T00:00:00'),today=new Date(now.getFullYear(),now.getMonth(),now.getDate()),thisB=new Date(now.getFullYear(),b.getMonth(),b.getDate()),diff=Math.round((thisB-today)/86400000);if(diff===0)bd=`<div class="card birthday"><h3>Сегодня день рождения</h3><p>${esc(state.user.nickname)}, поздравляем!</p></div>`;else if(diff===1)bd=`<div class="card birthday"><h3>День рождения завтра</h3><p>У ${esc(state.user.nickname)} день рождения завтра.</p></div>`}p.innerHTML=`<div class="hero"><h2>RAPID RESPONSE TEAM</h2><p>Закрытый портал подразделения [RRT]</p></div><br><div class="grid"><div class="card"><h3>Ваш доступ</h3><div class="stat">${esc(state.user.accessRoleName)}</div><p class="muted">ID: ${esc(state.user.id)}</p></div><div class="card"><h3>В отряде</h3><div class="stat">${serviceDays(state.user.joinedAt)} дней</div><p>${monthsLabel(serviceDays(state.user.joinedAt))}</p></div><div class="card"><h3>Дата вступления</h3><div class="stat">${state.user.joinedAt?esc(formatDate(state.user.joinedAt)):'—'}</div></div></div><br>${bd}`}
async function cabinet(p){const[m,h]=await Promise.all([api('/member?id='+encodeURIComponent(state.user.id)),api('/ranks?id='+encodeURIComponent(state.user.id))]);const u=m.user;p.innerHTML=`<div class="grid"><div class="card"><h3>Профиль</h3>${u.avatarUrl?`<img class="avatar big" src="${esc(u.avatarUrl)}">`:''}<p><b>Ник:</b> ${esc(u.nickname)}</p><p><b>Discord ID:</b> ${esc(u.id)}</p><p><b>Display name:</b> ${esc(u.displayName||'—')}</p><p><b>Discord username:</b> ${esc(u.discordUsername||'—')}</p><p><b>Global name:</b> ${esc(u.discordGlobalName||'—')}</p><p><b>Доступ:</b> ${esc(u.accessRoleName)}</p><p><b>Discord роли:</b> ${u.discordRoles.map(esc).join(', ')||'—'}</p></div><div class="card"><h3>Служба</h3><p><b>Вступление:</b> ${u.joinedAt?formatDate(u.joinedAt):'—'}</p><p><b>В отряде:</b> ${serviceDays(u.joinedAt)} дней / ${monthsLabel(serviceDays(u.joinedAt))}</p><p><b>День рождения:</b> ${u.birthDate?formatDate(u.birthDate):'не указан'}</p><p><b>Discord joined:</b> ${esc(u.discordJoinedAt||'—')}</p><p><b>Boost:</b> ${esc(u.discordBoostSince||'—')}</p><p><b>Pending:</b> ${u.discordPending?'Да':'Нет'}</p></div></div><br><div class="card"><h3>История званий</h3>${h.history.length?h.history.map(x=>`<div class="rank-event"><strong>${esc(x.changed_at)}</strong> — ${esc(x.old_rank||'—')} → <b>${esc(x.new_rank)}</b>${x.reason?`<div class="muted">${esc(x.reason)}</div>`:''}</div>`).join(''):'История пока пуста.'}</div>`}
async function roster(p){const d=await api('/members');p.innerHTML=`<div class="card"><h2>Состав отряда</h2><div class="table-wrap"><table class="table"><thead><tr><th>Игрок</th><th>Доступ</th><th>В отряде</th><th>День рождения</th></tr></thead><tbody>${d.members.map(x=>`<tr><td>${esc(x.nickname)}</td><td>${esc(x.access_role)}</td><td>${x.joined_at?serviceDays(x.joined_at)+' дней':'—'}</td><td>${x.birth_date?formatDate(x.birth_date):'—'}</td></tr>`).join('')}</tbody></table></div></div>`}
function rules(p){p.innerHTML=`<div class="card"><h2>Устав и правила</h2><div class="rules">${esc(RULES)}</div></div>`}
async function questionnaire(p){try{const d=await api('/questionnaire'),q=d.questionnaire;p.innerHTML=`<div class="card form"><h2>${esc(q.title)}</h2><p>${esc(q.description||'')}</p><form onsubmit="submitQ(event,${q.id})">${q.questions.map(x=>`<div class="field"><label>${esc(x.text)}${x.required?' *':''}</label>${x.type==='textarea'?`<textarea name="q${x.id}" rows="5"></textarea>`:x.type==='select'?`<select name="q${x.id}"><option value="">Выберите...</option>${x.options.map(o=>`<option>${esc(o)}</option>`).join('')}</select>`:`<input name="q${x.id}">`}</div>`).join('')}<button class="btn">ОТПРАВИТЬ</button></form></div>`}catch(e){p.innerHTML=`<div class="card danger"><h2>Опросник</h2><p>${esc(e.message)}</p></div>`}}
async function submitQ(e,id){e.preventDefault();const fd=new FormData(e.target),answers={};for(const[k,v]of fd)answers[k.slice(1)]=v;try{await api('/questionnaire/submit',{method:'POST',body:JSON.stringify({questionnaireId:id,answers})});alert('Опросник сохранён');e.target.reset()}catch(x){alert(x.message)}}
async function guideHome(p){p.innerHTML=`<div class="card"><h2>Руководства</h2><p>Сначала теория, затем короткая проверка только по этому блоку. Экзамена после курса нет.</p><div id="guideList" class="grid"></div></div>`;try{const d=await api('/guides');state.guides=d.guides;const el=document.querySelector('#guideList');el.innerHTML=[['ace_medical','ACE Medical','Медицина ACE.'],['movement','Порядок движения','Марш, контакт, триггер, здания и траншеи.']].map(([k,t,s])=>`<div class="card"><h3>${t}</h3><p>${s}</p><button class="btn" onclick="startGuide('${k}')">ОТКРЫТЬ</button></div>`).join('')}catch(e){document.querySelector('#guideList').innerHTML=`<div class="notice danger">${esc(e.message)}</div>`}}
async function startGuide(key){state.flash='';state.guideKey=key;const d=await api('/guide/progress?guide='+encodeURIComponent(key));state.progress=Object.fromEntries(d.progress.map(x=>[x.block_id,x]));const blocks=state.guides[key]||[];let next=blocks.findIndex(b=>!state.progress[b.id]?.completed);if(next<0)next=blocks.length-1;state.blockIndex=next;renderGuideBlock()}
async function renderGuideBlock(){const p=document.querySelector('#page'),blocks=state.guides[state.guideKey]||[],b=blocks[state.blockIndex];if(!b)return guideHome(p);const pr=state.progress[b.id]||{wrong_count:0,resets:0,locked:0,completed:0};p.innerHTML=`<div class="card"><button class="btn ghost" onclick="guideHome(document.querySelector('#page'))">← К руководствам</button>${state.flash?`<div class="notice danger"><b>${esc(state.flash)}</b></div>`:''}<div class="progressline">Блок ${state.blockIndex+1} из ${blocks.length} · ${pr.completed?'Пройден':'В процессе'}${pr.resets===2?' · ПОСЛЕДНЯЯ ПОПЫТКА':''}</div><h2>${esc(b.title)}</h2><div class="theory">${esc(b.theory)}</div>${b.imageUrl?`<img class="guide-image" loading="lazy" src="${esc(b.imageUrl)}" alt="Схема: ${esc(b.title)}" onclick="this.classList.toggle('zoom')">`:''}<div id="qbox"></div></div>`;if(pr.locked){document.querySelector('#qbox').innerHTML=`<div class="notice danger"><b>Обучение заблокировано.</b><br>Обратись к администратору. Только Штаб может сбросить попытки.</div>`;return}if(pr.completed){document.querySelector('#qbox').innerHTML=`<div class="notice">✓ Блок уже пройден.</div><button class="btn" onclick="nextGuideBlock()">СЛЕДУЮЩИЙ БЛОК</button>`;return}const qfull=await api('/guide/questions?guide='+encodeURIComponent(state.guideKey)+'&block='+b.id).catch(()=>null);if(qfull){state.questions=qfull.questions;state.qIndex=0;showQuestion()}else{await showQuestionFromFallback(b)}}
async function showQuestionFromFallback(b){document.querySelector('#qbox').innerHTML=`<div class="notice">Тест этого блока ещё не загружен.</div>`}
async function showQuestion(){const d=await api('/guide/questions?guide='+encodeURIComponent(state.guideKey)+'&block='+state.guides[state.guideKey][state.blockIndex].id);state.questions=d.questions;const q=state.questions[state.qIndex];document.querySelector('#qbox').innerHTML=`<div class="quiz"><div class="muted">Вопрос ${state.qIndex+1} из ${state.questions.length}</div><h3>${esc(q.question)}</h3><div class="answers">${q.options.map((o,i)=>`<button class="answer" onclick="answerGuide(${q.id},${i})">${esc(o)}</button>`).join('')}</div></div>`}
async function answerGuide(qid,idx){try{const b=state.guides[state.guideKey][state.blockIndex],d=await api('/guide/answer',{method:'POST',body:JSON.stringify({guideKey:state.guideKey,blockId:b.id,questionId:qid,answerIndex:idx})});const qbox=document.querySelector('#qbox');if(!d.correct){let msg='<div class="feedback bad"><b>Неправильно!</b><br>'+esc(d.explanation);if(d.reset)msg+='<br><br><b>'+esc(d.message)+'</b>';if(d.lastAttempt)msg+='<br><br><b>У тебя последняя попытка.</b>';if(d.locked)msg+='<br><br><b>Обучение заблокировано. Обратись к администратору.</b>';if(!d.reset&&!d.locked)msg+='<br><br><button class="btn" onclick="nextQuizQuestion()">СЛЕДУЮЩИЙ ВОПРОС</button>';qbox.innerHTML=msg;if(d.reset||d.locked)await refreshProgress(d.message||'Обучение заблокировано. Обратись к администратору.');return}qbox.innerHTML=`<div class="feedback good"><b>Правильно!</b><br>${esc(d.explanation)}</div>`;if(state.qIndex>=state.questions.length-1){const done=await api('/guide/complete',{method:'POST',body:JSON.stringify({guideKey:state.guideKey,blockId:b.id})});if(done.completed){await refreshProgress();setTimeout(nextGuideBlock,500);return}}state.qIndex++;setTimeout(showQuestion,350)}catch(e){alert(e.message)}}
function nextQuizQuestion(){state.qIndex++;showQuestion()}
async function refreshProgress(message=''){const d=await api('/guide/progress?guide='+encodeURIComponent(state.guideKey));state.progress=Object.fromEntries(d.progress.map(x=>[x.block_id,x]));state.flash=message;renderGuideBlock()}
function nextGuideBlock(){state.flash='';const blocks=state.guides[state.guideKey]||[];if(state.blockIndex<blocks.length-1){state.blockIndex++;renderGuideBlock()}else{document.querySelector('#page').innerHTML=`<div class="card"><h2>Руководство пройдено</h2><p>Все блоки этого руководства пройдены. Отдельного экзамена нет.</p><button class="btn" onclick="guideHome(document.querySelector('#page'))">К руководствам</button></div>`}}
function admin(p){p.innerHTML=`<div class="grid"><div class="card"><h3>Участники</h3><p>ID, ник, доступ, дата вступления, день рождения.</p><button class="btn" onclick="adminMemberForm()">Открыть</button></div><div class="card"><h3>Звания</h3><p>История точных дат повышений.</p><button class="btn" onclick="rankForm()">Открыть</button></div><div class="card"><h3>Опросники</h3><p>Просмотр отправленных анкет.</p><button class="btn" onclick="subs()">Открыть</button></div><div class="card"><h3>Discord</h3><p>Синхронизировать участников и роли.</p><button class="btn" onclick="syncDiscord()">СИНХРОНИЗИРОВАТЬ</button></div><div class="card"><h3>Попытки обучения</h3><p>Сбросить блок конкретному пользователю после блокировки.</p><button class="btn" onclick="resetGuideForm()">Открыть</button></div></div><br><div id="adminarea"></div>`}
function adminMemberForm(){document.querySelector('#adminarea').innerHTML=`<div class="card form"><h3>Участник</h3><div class="field"><label>Discord User ID</label><input id="a_id"></div><div class="field"><label>Nickname</label><input id="a_nick"></div><div class="field"><label>Display name</label><input id="a_disp"></div><div class="field"><label>Роль доступа</label><select id="a_role"><option value="ticket">С талончиком</option><option value="recruit">Рекрут</option><option value="unit">Отряд RRT</option><option value="officer">Офицер</option><option value="staff">Штаб</option></select></div><div class="field"><label>Дата вступления</label><input id="a_join" type="date"></div><div class="field"><label>Дата рождения</label><input id="a_birth" type="date"></div><button class="btn" onclick="saveMember()">Сохранить</button> <button class="btn ghost" onclick="issueActivation()">Выдать код активации</button></div>`}
async function saveMember(){try{await api('/admin/member',{method:'POST',body:JSON.stringify({id:a_id.value,nickname:a_nick.value,displayName:a_disp.value,accessRole:a_role.value,joinedAt:a_join.value||null,birthDate:a_birth.value||null})});alert('Сохранено')}catch(e){alert(e.message)}}
async function issueActivation(){try{const d=await api('/admin/activation',{method:'POST',body:JSON.stringify({userId:a_id.value})});alert('Одноразовый код: '+d.code)}catch(e){alert(e.message)}}
function rankForm(){document.querySelector('#adminarea').innerHTML=`<div class="card form"><h3>Изменение звания</h3><div class="field"><label>User ID</label><input id="r_uid"></div><div class="field"><label>Старое звание</label><input id="r_old"></div><div class="field"><label>Новое звание</label><input id="r_new"></div><div class="field"><label>Точная дата</label><input id="r_date" type="datetime-local"></div><div class="field"><label>Причина</label><textarea id="r_reason"></textarea></div><button class="btn" onclick="saveRank()">Зафиксировать</button></div>`}
async function saveRank(){try{await api('/admin/rank',{method:'POST',body:JSON.stringify({userId:r_uid.value,oldRank:r_old.value,newRank:r_new.value,changedAt:r_date.value,reason:r_reason.value})});alert('Записано')}catch(e){alert(e.message)}}
async function subs(){try{const d=await api('/admin/submissions');document.querySelector('#adminarea').innerHTML=`<div class="card"><h3>Ответы</h3><div class="table-wrap"><table class="table"><tr><th>Дата</th><th>Nickname</th><th>ID</th><th>Опросник</th></tr>${d.submissions.map(x=>`<tr><td>${new Date(x.submitted_at*1000).toLocaleString('ru-RU')}</td><td>${esc(x.nickname)}</td><td>${esc(x.user_id)}</td><td>${esc(x.title)}</td></tr>`).join('')}</table></div></div>`}catch(e){alert(e.message)}}
async function syncDiscord(){try{const d=await api('/admin/sync-discord',{method:'POST'});alert('Синхронизировано: '+d.total)}catch(e){alert(e.message)}}
function resetGuideForm(){document.querySelector('#adminarea').innerHTML=`<div class="card form"><h3>Сброс попыток</h3><div class="field"><label>User ID</label><input id="g_uid"></div><div class="field"><label>Руководство</label><select id="g_key"><option value="ace_medical">ACE Medical</option><option value="movement">Порядок движения</option></select></div><div class="field"><label>Номер блока</label><input id="g_block" type="number" min="1"></div><button class="btn red" onclick="resetGuide()">СБРОСИТЬ ПОПЫТКИ</button></div>`}
async function resetGuide(){try{await api('/admin/guide/reset',{method:'POST',body:JSON.stringify({userId:g_uid.value,guideKey:g_key.value,blockId:Number(g_block.value)})});alert('Попытки сброшены')}catch(e){alert(e.message)}}
boot();